### ISSUE TITLE
Mike Tyson's Punch Out - Glitched out graphics

### ISSUE THREAD

**Issue by NightScript370** [DS-Homebrew/NesDS#2]
The ring in Punch Out is glitchy on nesDS, as tested by SleepyLark. The reason seems to be PPU fetches. If the PPU does not fetch the 34th tile, the ring will be glitched. ([Source](http://wiki.nesdev.com/w/index.php/Tricky-to-emulate_games))

**Comment by ghost** [comment]
Fixed in my branch though 2 of the fights the sprite/CHR glitch out a bit put on PureSoft for these.

EDIT: Now has been merged with this repo and the release page should have the binary!

https://github.com/DS-Homebrew/NesDS/commit/d1f8a2dc587e0f3700e946b6161a18ed1def710f
