### ISSUE TITLE
nesDS.cia not working

### ISSUE THREAD

**Issue by GeAd23** [DS-Homebrew/NesDS#9]
I have installed the nesDS.cia.
But if I run the software, it tells me, “A failure has occurred. Please hold the Power button to turn the system off.”.
If I run the nesDS.nds file over TWMenu++, all is working fine.
It is something that I do wrong ?

Your sincerely

**Comment by RocketRobz** [comment]
If you're using EmuNAND, you need to either install the CIA to SysNAND, or transfer your EmuNAND to SysNAND.
https://3ds.hacks.guide/move-emunand

**Comment by GeAd23** [comment]
I installed the nesDS.cia via FBI. And I don’t have a drive (E:) EmuNAND in godmode9. I test it with a  3DS and New 2DS XL. Both give me the same error. 

Yours Sincerely

**Comment by GeAd23** [comment]
All my software is installed in the SysNand. If you have an idea why only the nesDS.cia don’t work, tell me please. @RocketRobz
The nesDS.nds works fine. And other cias like FBI or Checkpoint works all without problems. 

Yours Sincerely

**Comment by GeAd23** [comment]
An answer can be helpful @RocketRobz

Yours Sincerely

**Comment by RocketRobz** [comment]
> An answer can be helpful @RocketRobz Yours Sincerely

We'll look into the issue when we have the time.

**Comment by RocketRobz** [comment]
Fixed by fbdfee8
